# Generated by Django 3.1.4 on 2021-02-02 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import eevie.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eevie', '0002_auto_20210104_0216'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACcharger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usable_phases', models.IntegerField()),
                ('max_power', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='AddressInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('addressLine', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
                ('stateOrProvince', models.CharField(max_length=100)),
                ('postCode', models.IntegerField()),
                ('countryId', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longtitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('contact_telephone', models.CharField(max_length=13)),
                ('access_comments', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='chargingCurve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField(validators=[eevie.validators.validate_percentage])),
                ('power', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_url', models.URLField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ports',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StatusType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('IsOperational', models.BooleanField()),
                ('Title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UsageType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('IsPayAtLocation', models.BooleanField()),
                ('IsMembershipRequired', models.BooleanField()),
                ('IsAccessKeyRequired', models.BooleanField()),
                ('Title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='monthlybill',
            name='customer',
        ),
        migrations.AddField(
            model_name='monthlybill',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthlybills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('photo', models.URLField()),
                ('generalComments', models.CharField(max_length=1000)),
                ('isOperational', models.BooleanField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('addressInfo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='belongs_to', to='eevie.addressinfo')),
                ('operators', models.ManyToManyField(related_name='operates', to='eevie.Operator')),
                ('ports', models.ManyToManyField(related_name='exist_at', to='eevie.Ports')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.TimeField()),
                ('total_kwh', models.FloatField()),
                ('cost', models.FloatField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DCcharger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_power', models.FloatField()),
                ('charging_curve', models.ManyToManyField(to='eevie.chargingCurve')),
                ('ports', models.ManyToManyField(to='eevie.Ports')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=100)),
                ('release_year', models.IntegerField(validators=[eevie.validators.validate_year])),
                ('usable_battery_size', models.FloatField(validators=[eevie.validators.validate_percentage])),
                ('average_consumption', models.FloatField(validators=[eevie.validators.validate_percentage])),
                ('ac_charger', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='eevie.accharger')),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='eevie.brands')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL)),
                ('dc_charger', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='eevie.dccharger')),
            ],
        ),
        migrations.AddField(
            model_name='accharger',
            name='ports',
            field=models.ManyToManyField(to='eevie.Ports'),
        ),
    ]
