# Generated by Django 3.1.4 on 2021-02-03 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eevie', '0003_auto_20210202_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckinStatus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='station',
            name='isOperational',
        ),
        migrations.RemoveField(
            model_name='station',
            name='ports',
        ),
        migrations.RemoveField(
            model_name='station',
            name='rating',
        ),
        migrations.AddField(
            model_name='car',
            name='type',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='statusType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eevie.statustype'),
        ),
        migrations.AddField(
            model_name='station',
            name='usageCost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='usageType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eevie.usagetype'),
        ),
        migrations.AlterField(
            model_name='addressinfo',
            name='access_comments',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='addressinfo',
            name='contact_telephone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='operator',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='station',
            name='generalComments',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statustype',
            name='IsOperational',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usagetype',
            name='IsAccessKeyRequired',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usagetype',
            name='IsMembershipRequired',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usagetype',
            name='IsPayAtLocation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UserComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('rating', models.IntegerField()),
                ('checkinStatus', models.ManyToManyField(to='eevie.CheckinStatus')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myComments', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserComments', to='eevie.station')),
            ],
        ),
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('voltage', models.IntegerField(blank=True, null=True)),
                ('powerKW', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('current_type', models.ManyToManyField(blank=True, related_name='exists_at', to='eevie.CurrentType')),
                ('ports', models.ManyToManyField(related_name='exist_at', to='eevie.Ports')),
                ('status_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eevie.statustype')),
            ],
        ),
        migrations.AddField(
            model_name='station',
            name='connections',
            field=models.ManyToManyField(to='eevie.Connections'),
        ),
    ]
