# Generated by Django 3.1.4 on 2021-02-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eevie', '0004_auto_20210203_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accharger',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chargingcurve',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dccharger',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usercomments',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
