# Generated by Django 3.1.4 on 2021-02-03 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eevie', '0005_auto_20210203_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accharger',
            old_name='id',
            new_name='idd',
        ),
    ]
