# Generated by Django 3.1.4 on 2021-02-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eevie', '0007_auto_20210203_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accharger',
            name='ports',
            field=models.ManyToManyField(related_name='portas', to='eevie.Ports'),
        ),
    ]
