# Generated by Django 3.1.4 on 2021-02-03 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eevie', '0008_auto_20210203_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='ac_charger',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='eevie.accharger'),
        ),
        migrations.AlterField(
            model_name='car',
            name='dc_charger',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='eevie.dccharger'),
        ),
    ]
