# Generated by Django 3.1.4 on 2021-02-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eevie', '0013_auto_20210203_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressinfo',
            name='postCode',
            field=models.CharField(max_length=10),
        ),
    ]
