# Generated by Django 3.1.4 on 2021-02-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eevie', '0014_auto_20210204_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressinfo',
            name='stateOrProvince',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
