# Generated by Django 3.1.4 on 2021-02-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eevie', '0016_auto_20210204_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressinfo',
            name='town',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
