# Generated by Django 3.1.4 on 2021-02-04 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eevie', '0018_auto_20210204_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='addressInfo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='belongs_to', to='eevie.addressinfo'),
        ),
    ]
