# Generated by Django 3.1.4 on 2021-02-04 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eevie', '0021_auto_20210204_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connections',
            name='status_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eevie.statustype'),
        ),
    ]
