# Generated by Django 3.1.4 on 2021-02-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eevie', '0022_auto_20210204_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='operator',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='operator',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
