# Generated by Django 3.1.4 on 2021-02-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eevie', '0023_auto_20210204_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connections',
            name='current_type',
            field=models.ManyToManyField(blank=True, null=True, related_name='exists_at', to='eevie.CurrentType'),
        ),
        migrations.AlterField(
            model_name='connections',
            name='ports',
            field=models.ManyToManyField(null=True, related_name='exist_at', to='eevie.Ports'),
        ),
        migrations.AlterField(
            model_name='connections',
            name='powerKW',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='connections',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
