# Generated by Django 3.1.4 on 2021-02-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eevie', '0025_auto_20210204_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomments',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
