# Generated by Django 3.1.4 on 2021-02-28 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eevie', '0026_auto_20210204_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='session',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='session',
            name='total_kwh',
        ),
        migrations.AddField(
            model_name='session',
            name='connectionTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='disconnectTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='doneChargingTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='kWhDelivered',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='port',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='eevie.ports'),
        ),
        migrations.AddField(
            model_name='session',
            name='station',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='eevie.station'),
        ),
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WhPerMile', models.IntegerField(null=True)),
                ('kWhRequested', models.FloatField(null=True)),
                ('milesRequested', models.IntegerField(null=True)),
                ('minutesAvailable', models.IntegerField(null=True)),
                ('modifiedAt', models.DateTimeField(null=True)),
                ('requestedDeparture', models.DateTimeField(null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userInputs', to='eevie.session')),
            ],
        ),
    ]
