# Generated by Django 3.1.4 on 2021-02-28 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eevie', '0027_auto_20210228_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('costPerkWh', models.FloatField()),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='connections',
            name='status_type',
        ),
        migrations.AddField(
            model_name='connections',
            name='status_type',
            field=models.ManyToManyField(blank=True, to='eevie.StatusType'),
        ),
        migrations.RemoveField(
            model_name='station',
            name='statusType',
        ),
        migrations.AddField(
            model_name='station',
            name='statusType',
            field=models.ManyToManyField(blank=True, to='eevie.StatusType'),
        ),
        migrations.RemoveField(
            model_name='station',
            name='usageType',
        ),
        migrations.AddField(
            model_name='station',
            name='usageType',
            field=models.ManyToManyField(blank=True, to='eevie.UsageType'),
        ),
        migrations.AddField(
            model_name='session',
            name='provider',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hasmade', to='eevie.provider'),
        ),
        migrations.AddField(
            model_name='station',
            name='providers',
            field=models.ManyToManyField(related_name='providers', to='eevie.Provider'),
        ),
    ]
