# Generated by Django 3.1.4 on 2021-03-01 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eevie', '0028_auto_20210228_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='port',
        ),
    ]
