# Generated by Django 3.1.4 on 2021-03-01 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eevie', '0031_auto_20210301_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='provider',
        ),
        migrations.AddField(
            model_name='session',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hasmade', to='eevie.provider'),
        ),
    ]
