# Generated by Django 3.1.4 on 2021-03-01 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eevie', '0036_auto_20210301_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('voltage', models.IntegerField(blank=True, null=True)),
                ('powerKW', models.FloatField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('current_type', models.ManyToManyField(blank=True, related_name='exists_at', to='eevie.CurrentType')),
            ],
        ),
        migrations.RemoveField(
            model_name='station',
            name='connections',
        ),
        migrations.DeleteModel(
            name='Connections',
        ),
        migrations.AddField(
            model_name='point',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='points', to='eevie.station'),
        ),
        migrations.AddField(
            model_name='point',
            name='status_type',
            field=models.ManyToManyField(blank=True, to='eevie.StatusType'),
        ),
    ]
