# Generated by Django 3.1.4 on 2021-03-01 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eevie', '0039_point_ports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='ports',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eevie.ports'),
        ),
    ]
