# Generated by Django 3.1.4 on 2021-03-01 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eevie', '0042_auto_20210301_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points', to='eevie.point'),
        ),
        migrations.AddField(
            model_name='session',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='eevie.car'),
        ),
    ]
