# Generated by Django 3.1.4 on 2021-03-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eevie', '0043_auto_20210301_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='protocol',
            field=models.CharField(default='Level 2 : Medium (Over 2kW)', max_length=20),
        ),
    ]
