# Generated by Django 3.1.4 on 2021-03-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eevie', '0044_point_protocol'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='payment',
            field=models.CharField(choices=[('Cash', 'PayinCash'), ('Debit Card', 'PaywithCard'), ('Credit', 'Payattheendofmonth')], default='Cash', max_length=10),
        ),
    ]
