# Generated by Django 3.1.4 on 2021-03-07 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eevie', '0045_session_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlybill',
            name='end_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='points', to='eevie.point'),
        ),
        migrations.AlterField(
            model_name='session',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sessions', to='eevie.station'),
        ),
        migrations.AlterField(
            model_name='session',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vehicle', to='eevie.car'),
        ),
    ]
