# Generated by Django 3.1.4 on 2021-03-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eevie', '0046_auto_20210307_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlybill',
            name='monthly_total',
            field=models.FloatField(default=0),
        ),
    ]
