# Generated by Django 3.1.4 on 2021-02-03 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eevie', '0009_auto_20210203_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='eevie.brands'),
        ),
    ]
