# Generated by Django 3.1.4 on 2021-02-03 19:42

from django.db import migrations, models
import eevie.validators


class Migration(migrations.Migration):

    dependencies = [
        ('eevie', '0012_auto_20210203_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='release_year',
            field=models.IntegerField(null=True, validators=[eevie.validators.validate_year]),
        ),
    ]
