# Generated by Django 3.1.4 on 2021-02-04 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eevie', '0019_auto_20210204_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='statusType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eevie.statustype'),
        ),
        migrations.AlterField(
            model_name='station',
            name='usageType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eevie.usagetype'),
        ),
    ]
