# Generated by Django 3.1.4 on 2021-02-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eevie', '0024_auto_20210204_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connections',
            name='current_type',
            field=models.ManyToManyField(blank=True, related_name='exists_at', to='eevie.CurrentType'),
        ),
        migrations.AlterField(
            model_name='connections',
            name='ports',
            field=models.ManyToManyField(related_name='exist_at', to='eevie.Ports'),
        ),
    ]
