# Generated by Django 3.1.4 on 2021-03-01 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eevie', '0033_auto_20210301_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinput',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userInputs', to='eevie.session'),
        ),
    ]
