# Generated by Django 3.1.4 on 2021-03-01 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eevie', '0038_auto_20210301_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='ports',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eevie.ports'),
        ),
    ]
