# Generated by Django 3.1.4 on 2021-03-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eevie', '0041_auto_20210301_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='ports',
        ),
        migrations.AddField(
            model_name='point',
            name='ports',
            field=models.ManyToManyField(related_name='exist_at', to='eevie.Ports'),
        ),
    ]
